version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    restart: always
  db:
    image: mongo
    volumes:
      - './database:/data/db'
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - app
